# backend/agents/crisis_agent.py
# Handles emergency situations with structured, prioritized responses

from langchain_google_genai import ChatGoogleGenerativeAI
from langchain.prompts import PromptTemplate
from langchain_core.output_parsers import JsonOutputParser
from pydantic import BaseModel, Field
from typing import List
from backend.core.config import settings
from backend.services.document_service import document_service
from backend.db.models import Patient, Medicine, Doctor
from sqlalchemy.orm import Session


# ── Structured Output Schema ──────────────────────────────────────
# This tells LangChain exactly what format we expect from Gemini
# Gemini MUST return JSON matching this structure

class CrisisResponse(BaseModel):
    """
    Structured response for crisis situations.
    Every field is required — no ambiguity in emergencies.
    """
    call_ambulance: bool = Field(
        description="Whether to call an ambulance immediately"
    )
    immediate_steps: List[str] = Field(
        description="List of immediate actions to take right now, in order"
    )
    possible_causes: List[str] = Field(
        description="Possible causes based on patient's conditions and medicines — NOT a diagnosis"
    )
    what_to_tell_doctor: str = Field(
        description="Key information to tell the ER doctor when arriving"
    )
    reassurance: str = Field(
        description="Calm, reassuring message for the worried family member"
    )


class CrisisAgent:
    def __init__(self):
        """
        Sets up LangChain with Gemini.

        Why LangChain here instead of direct SDK?
        LangChain's JsonOutputParser reliably extracts structured JSON
        from Gemini's response — critical when we need predictable
        fields like call_ambulance and immediate_steps every single time.
        """
        self.llm = ChatGoogleGenerativeAI(
            model="gemini-2.5-flash",
            google_api_key=settings.GEMINI_API_KEY,
            temperature=0.1
            # temperature=0.1 means very low creativity/randomness
            # In emergencies we want consistent, reliable responses
            # not creative ones
        )
        self.parser = JsonOutputParser(pydantic_object=CrisisResponse)

    def get_patient_data(self, patient_id: int, db: Session) -> dict:
        """
        Fetches complete patient data for crisis context.
        Returns a dict with patient, medicines, and doctors.
        We need everything — in a crisis, incomplete info is dangerous.
        """
        patient = db.query(Patient).filter(Patient.id == patient_id).first()
        if not patient:
            return None

        medicines = db.query(Medicine).filter(
            Medicine.patient_id == patient_id,
            Medicine.active == True
        ).all()

        doctors = db.query(Doctor).filter(
            Doctor.patient_id == patient_id
        ).all()

        return {
            "patient": patient,
            "medicines": medicines,
            "doctors": doctors
        }

    def generate_emergency_card(self, patient_data: dict, symptoms: str, crisis_response: dict) -> str:
        """
        Generates a formatted emergency card as plain text.

        Why plain text and not JSON?
        This card needs to be readable instantly by an ER doctor
        on a phone screen at 2am. Clean, simple, no formatting noise.
        """
        patient = patient_data["patient"]
        medicines = patient_data["medicines"]
        doctors = patient_data["doctors"]

        card = f"""
╔══════════════════════════════════════╗
       CARECONNECT EMERGENCY CARD
╚══════════════════════════════════════╝

PATIENT: {patient.name}, {patient.age}M, {patient.blood_group}
CONDITIONS: {patient.conditions}
ALLERGIES: {patient.allergies}

REPORTED SYMPTOMS:
{symptoms}

CURRENT MEDICINES:
"""
        for med in medicines:
            card += f"  • {med.name} {med.dosage} — {med.timing}\n"

        card += "\nDOCTOR(S) TO CONTACT:\n"
        for doc in doctors:
            card += f"  • {doc.name} ({doc.specialization})\n"
            card += f"    {doc.hospital} — {doc.phone}\n"

        card += f"""
IMMEDIATE STEPS TAKEN:
"""
        for i, step in enumerate(crisis_response.get("immediate_steps", []), 1):
            card += f"  {i}. {step}\n"

        card += f"""
WHAT TO TELL ER DOCTOR:
{crisis_response.get('what_to_tell_doctor', '')}

Generated by CareConnect
══════════════════════════════════════
"""
        return card

    def analyze_crisis(self, symptoms: str, patient_id: int, db: Session) -> dict:
        """
        Main crisis analysis function.

        Flow:
        1. Get complete patient data
        2. Search documents for relevant medical history
        3. Build crisis prompt with all context
        4. Get structured response from Gemini
        5. Generate emergency card
        6. Return everything the family needs
        """
        # Step 1: Get patient data
        patient_data = self.get_patient_data(patient_id, db)
        if not patient_data:
            return {"error": "Patient not found"}

        patient = patient_data["patient"]
        medicines = patient_data["medicines"]
        doctors = patient_data["doctors"]

        # Step 2: Search documents for relevant history
        doc_results = document_service.search_documents(
            patient_id=patient_id,
            query=symptoms,
            n_results=3
        )

        doc_context = ""
        if doc_results:
            doc_context = "RELEVANT MEDICAL HISTORY FROM DOCUMENTS:\n"
            for chunk in doc_results:
                doc_context += f"(From {chunk['filename']}): {chunk['text']}\n\n"

        # Step 3: Build medicines and doctors context
        med_context = "\n".join([
            f"- {m.name} {m.dosage} ({m.timing})" for m in medicines
        ])

        doc_list = "\n".join([
            f"- {d.name} ({d.specialization}) at {d.hospital}, Phone: {d.phone}"
            for d in doctors
        ])

        # Step 4: Build crisis prompt
        # format_instructions tells Gemini exactly what JSON to return
        format_instructions = self.parser.get_format_instructions()

        prompt = f"""You are CareConnect's Crisis Support Agent.
A family member needs IMMEDIATE help. Stay calm, be clear, be actionable.

CRITICAL RULES:
1. NEVER diagnose — only suggest possible causes based on known conditions
2. When in doubt, recommend calling ambulance (err on side of caution)
3. Be specific and actionable — no vague advice
4. Consider the patient's current medicines — symptoms might be side effects

PATIENT: {patient.name}, Age: {patient.age}, Blood Group: {patient.blood_group}
CONDITIONS: {patient.conditions}
ALLERGIES: {patient.allergies}

CURRENT MEDICINES:
{med_context}

DOCTORS:
{doc_list}

{doc_context}

REPORTED SYMPTOMS:
{symptoms}

{format_instructions}

Analyze the situation and respond with the JSON structure above.
Remember: you are NOT diagnosing. You are helping a scared family member
take the right immediate actions based on known medical context."""

        # Step 5: Get structured response from Gemini
        response = self.llm.invoke(prompt)
        crisis_response = self.parser.parse(response.content)

        # Step 6: Generate emergency card
        emergency_card = self.generate_emergency_card(
            patient_data, symptoms, crisis_response
        )

        return {
            "symptoms": symptoms,
            "patient_name": patient.name,
            "call_ambulance": crisis_response.get("call_ambulance", False),
            "immediate_steps": crisis_response.get("immediate_steps", []),
            "possible_causes": crisis_response.get("possible_causes", []),
            "what_to_tell_doctor": crisis_response.get("what_to_tell_doctor", ""),
            "reassurance": crisis_response.get("reassurance", ""),
            "emergency_card": emergency_card
        }


# Single instance
crisis_agent = CrisisAgent()